application: lot-spreadsheet
version: 1
runtime: go
api_version: go1

handlers:
  - url: /(.*\.(js|css|html|mem))$
    static_files: static/\1
    upload: static/.*\.(js|css|html|mem)$
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /.*
    script: _go_app